version: "3"
networks:
    application:
        driver: bridge
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mybackend
        ports:
            - 8000:8000
        volumes:
            - ./backend:/app
        depends_on:
            - db
        environment:
            - DB_HOST=mysql
        networks:
            - application
        entrypoint: ["/bin/sh", "-c"]
        command:
            - |
                composer install
                php artisan migrate
                php artisan serve --host=0.0.0.0 --port=8000
    db:
    image: mysql:8.0
    ports:
        - "3306:3306"
    volumes:
        - ./data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
        - application
    container_name: mysqldb
    healthcheck:
        test: ["CMD-SHELL", "mysqladmin ping -u root -p ${MYSQL_PASSWORD}"]
        interval: 5s
        timeout: 5s
        retries: 5
